import Foundation

/// One record from the NTFS USN change journal (`$Extend\$UsnJrnl:$J`) - a single
/// change to one file or directory.
///
/// The journal is forensic gold: it records **creates, deletes, and renames by
/// name even after the file (and its MFT entry) are gone**, recovering deleted/
/// renamed filenames the live filesystem no longer shows. Its timestamps are
/// generated by NTFS at the moment of change and are **not user-settable**, so it
/// captures the very anti-forensic activity (delete + timestomp) other artifacts
/// miss. Create-then-delete and rename sequences expose staging, exfil cleanup,
/// and masquerading.
public nonisolated struct UsnRecord: Identifiable, Hashable, Sendable, Codable {
    public let id: UUID
    /// Update Sequence Number (monotonic offset within the journal).
    public let usn: UInt64
    /// When the change happened (NTFS-generated FILETIME); nil if unset.
    public let timestamp: Date?
    /// The changed file/dir's own (leaf) name - recovered even for deletes.
    public let fileName: String
    public let isDirectory: Bool
    /// MFT entry of the changed file (low 48 bits of the file reference).
    public let mftEntry: UInt64
    /// MFT sequence number (high 16 bits) - distinguishes a recovered name from
    /// a since-reused MFT slot.
    public let mftSequence: UInt16
    /// MFT entry of the parent directory (for path reconstruction with a `$MFT`).
    public let parentMftEntry: UInt64
    /// Raw USN reason bitmask.
    public let reasonRaw: UInt32
    /// Raw NTFS file-attribute bitmask.
    public let fileAttributes: UInt32
    /// Source `$J` stream path.
    public let sourceFile: String

    public init(id: UUID = UUID(), usn: UInt64, timestamp: Date?, fileName: String,
                isDirectory: Bool, mftEntry: UInt64, mftSequence: UInt16, parentMftEntry: UInt64,
                reasonRaw: UInt32, fileAttributes: UInt32, sourceFile: String) {
        self.id = id
        self.usn = usn
        self.timestamp = timestamp
        self.fileName = fileName
        self.isDirectory = isDirectory
        self.mftEntry = mftEntry
        self.mftSequence = mftSequence
        self.parentMftEntry = parentMftEntry
        self.reasonRaw = reasonRaw
        self.fileAttributes = fileAttributes
        self.sourceFile = sourceFile
    }

    public var isCreate: Bool { reasonRaw & UsnReason.fileCreate != 0 }
    public var isDelete: Bool { reasonRaw & UsnReason.fileDelete != 0 }
    public var isRename: Bool { reasonRaw & (UsnReason.renameOldName | UsnReason.renameNewName) != 0 }

    /// Human-readable change reasons, e.g. ["File create", "Close"].
    public var reasonLabels: [String] { UsnReason.labels(for: reasonRaw) }
    public var reasonSummary: String { reasonLabels.joined(separator: ", ") }

    /// File extension (lowercased), for analyzer gating.
    public var fileExtension: String {
        (fileName as NSString).pathExtension.lowercased()
    }
}

/// USN reason bitmask flags + decoding.
public nonisolated enum UsnReason {
    public static let dataOverwrite: UInt32   = 0x0000_0001
    public static let dataExtend: UInt32      = 0x0000_0002
    public static let dataTruncation: UInt32  = 0x0000_0004
    public static let fileCreate: UInt32      = 0x0000_0100
    public static let fileDelete: UInt32      = 0x0000_0200
    public static let eaChange: UInt32        = 0x0000_0400
    public static let securityChange: UInt32  = 0x0000_0800
    public static let renameOldName: UInt32   = 0x0000_1000
    public static let renameNewName: UInt32   = 0x0000_2000
    public static let basicInfoChange: UInt32 = 0x0000_8000
    public static let hardLinkChange: UInt32  = 0x0001_0000
    public static let objectIDChange: UInt32  = 0x0008_0000
    public static let reparseChange: UInt32   = 0x0010_0000
    public static let streamChange: UInt32    = 0x0020_0000
    public static let close: UInt32           = 0x8000_0000

    private static let table: [(UInt32, String)] = [
        (dataOverwrite, "Data overwrite"), (dataExtend, "Data extend"),
        (dataTruncation, "Data truncation"), (fileCreate, "File create"),
        (fileDelete, "File delete"), (eaChange, "EA change"),
        (securityChange, "Security change"), (renameOldName, "Rename (old name)"),
        (renameNewName, "Rename (new name)"), (basicInfoChange, "Basic info change"),
        (hardLinkChange, "Hard link change"), (objectIDChange, "Object ID change"),
        (reparseChange, "Reparse point change"), (streamChange, "Stream change"),
        (close, "Close"),
    ]

    public static func labels(for mask: UInt32) -> [String] {
        table.compactMap { mask & $0.0 != 0 ? $0.1 : nil }
    }
}
