import Foundation

/// Renders a `CoCReportModel` to HTML or Markdown. Self-contained HTML (inline,
/// print-friendly CSS) so a later WebKit `createPDF` pass needs no extra layout.
public nonisolated enum CoCReportRenderer {

    // MARK: - HTML

    public static func html(_ model: CoCReportModel) -> String {
        let esc = HTMLReportRenderer.escape
        var out = ""
        out += "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
        out += "<title>Strata Chain of Custody — \(esc(model.caseName))</title>\n"
        out += "<style>\n\(css)\n</style>\n</head>\n<body>\n"

        out += "<header class=\"case-header\">\n"
        out += "<h1>Strata Chain-of-Custody Report</h1>\n"
        out += "<p class=\"subtitle\">\(esc(model.caseName))</p>\n"
        out += "<table class=\"meta\">\n"
        out += metaRow("Examiner", model.examiner.isEmpty ? "—" : model.examiner)
        out += metaRow("Case created", ReportFormat.display(model.createdAt))
        out += metaRow("Report generated", ReportFormat.display(model.generatedAt))
        out += metaRow("Evidence items", String(model.evidence.count))
        out += metaRow("Custody log entries", String(model.log.count))
        out += "</table>\n"
        out += "<p class=\"note\">All timestamps are ISO-8601 / UTC. This is an append-only custody record.</p>\n"
        out += "</header>\n"

        out += "<h2>Evidence integrity</h2>\n"
        if model.evidence.isEmpty {
            out += "<p class=\"empty\">No evidence.</p>\n"
        }
        for ev in model.evidence {
            out += "<section class=\"evidence\">\n"
            out += "<h3>\(esc(ev.displayName))</h3>\n"
            out += "<p class=\"source\"><strong>Source:</strong> \(esc(ev.kindLabel)) — <code>\(esc(ev.sourcePath))</code></p>\n"

            out += "<h4>Acquisition</h4>\n"
            if let acq = ev.acquisition, !acq.isEmpty {
                out += "<table class=\"meta\">\n"
                func row(_ l: String, _ v: String) { if !v.isEmpty { out += metaRow(l, v) } }
                row("Examiner", acq.examiner)
                row("Tool", acq.acquisitionTool)
                row("Method", acq.acquisitionMethod)
                if let d = acq.acquiredAt { out += metaRow("Acquired", ReportFormat.display(d)) }
                row("Case number", acq.caseNumber)
                row("Media serial", acq.mediaSerial)
                row("Notes", acq.notes)
                out += metaRow("Provenance", provenanceLabel(acq.source))
                out += "</table>\n"
            } else {
                out += "<p class=\"empty\">No acquisition metadata recorded.</p>\n"
            }

            out += "<h4>Source hashes</h4>\n"
            if ev.hashes.isEmpty {
                out += "<p class=\"empty\">No source hashes recorded.</p>\n"
            } else {
                out += "<table class=\"data\">\n<thead><tr>"
                out += "<th>Algorithm</th><th>Value</th><th>Origin</th><th>Status</th>"
                out += "</tr></thead>\n<tbody>\n"
                for h in ev.hashes {
                    out += "<tr>"
                    out += "<td>\(esc(h.algorithm.label))</td>"
                    out += "<td><code>\(esc(h.value))</code></td>"
                    out += "<td>\(esc(h.origin.label))</td>"
                    out += "<td>\(esc(h.status.label))</td>"
                    out += "</tr>\n"
                }
                out += "</tbody>\n</table>\n"
            }
            out += "</section>\n"
        }

        out += "<h2>Custody log</h2>\n"
        if model.log.isEmpty {
            out += "<p class=\"empty\">No recorded events.</p>\n"
        } else {
            out += "<table class=\"data\">\n<thead><tr>"
            out += "<th>Timestamp</th><th>Action</th><th>Evidence</th><th>Actor</th><th>Detail</th>"
            out += "</tr></thead>\n<tbody>\n"
            for e in model.log {
                out += "<tr>"
                out += "<td>\(esc(ReportFormat.display(e.timestamp)))</td>"
                out += "<td>\(esc(e.action))</td>"
                out += "<td>\(esc(e.evidenceName ?? "—"))</td>"
                out += "<td>\(esc(e.actor))</td>"
                out += "<td>\(esc(e.detail))</td>"
                out += "</tr>\n"
            }
            out += "</tbody>\n</table>\n"
        }

        out += "<footer>Generated by Strata.</footer>\n</body>\n</html>\n"
        return out
    }

    // MARK: - Markdown

    public static func markdown(_ model: CoCReportModel) -> String {
        var out = ""
        out += "# Strata Chain-of-Custody Report — \(model.caseName)\n\n"
        out += "| | |\n|---|---|\n"
        out += "| Case | \(md(model.caseName)) |\n"
        out += "| Examiner | \(md(model.examiner.isEmpty ? "—" : model.examiner)) |\n"
        out += "| Case created | \(ReportFormat.display(model.createdAt)) |\n"
        out += "| Report generated | \(ReportFormat.display(model.generatedAt)) |\n"
        out += "| Evidence items | \(model.evidence.count) |\n"
        out += "| Custody log entries | \(model.log.count) |\n"
        out += "\n_All timestamps are ISO-8601 / UTC. This is an append-only custody record._\n\n"

        out += "## Evidence integrity\n\n"
        if model.evidence.isEmpty { out += "_No evidence._\n\n" }
        for ev in model.evidence {
            out += "### \(md(ev.displayName))\n\n"
            out += "**Source:** \(md(ev.kindLabel)) — `\(ev.sourcePath)`\n\n"
            out += "**Acquisition**\n\n"
            if let acq = ev.acquisition, !acq.isEmpty {
                out += "| Field | Value |\n|---|---|\n"
                func row(_ l: String, _ v: String) { if !v.isEmpty { out += "| \(l) | \(md(v)) |\n" } }
                row("Examiner", acq.examiner)
                row("Tool", acq.acquisitionTool)
                row("Method", acq.acquisitionMethod)
                if let d = acq.acquiredAt { out += "| Acquired | \(ReportFormat.display(d)) |\n" }
                row("Case number", acq.caseNumber)
                row("Media serial", acq.mediaSerial)
                row("Notes", acq.notes)
                out += "| Provenance | \(provenanceLabel(acq.source)) |\n\n"
            } else {
                out += "_No acquisition metadata recorded._\n\n"
            }
            out += "**Source hashes**\n\n"
            if ev.hashes.isEmpty {
                out += "_No source hashes recorded._\n\n"
            } else {
                out += "| Algorithm | Value | Origin | Status |\n|---|---|---|---|\n"
                for h in ev.hashes {
                    out += "| \(h.algorithm.label) | `\(h.value)` | \(h.origin.label) | \(h.status.label) |\n"
                }
                out += "\n"
            }
        }

        out += "## Custody log\n\n"
        if model.log.isEmpty {
            out += "_No recorded events._\n"
        } else {
            out += "| Timestamp | Action | Evidence | Actor | Detail |\n|---|---|---|---|---|\n"
            for e in model.log {
                out += "| \(ReportFormat.display(e.timestamp)) | \(md(e.action)) | \(md(e.evidenceName ?? "—")) | \(md(e.actor)) | \(md(e.detail)) |\n"
            }
            out += "\n"
        }

        out += "---\n\n_Generated by Strata._\n"
        return out
    }

    // MARK: - Helpers

    private static func provenanceLabel(_ source: AcquisitionInfo.Source) -> String {
        switch source {
        case .manual:      return "Examiner-entered"
        case .ewfMetadata: return "Auto (E01 header)"
        case .mixed:       return "Auto + edited"
        }
    }

    private static func metaRow(_ label: String, _ value: String) -> String {
        "<tr><th>\(HTMLReportRenderer.escape(label))</th><td>\(HTMLReportRenderer.escape(value))</td></tr>\n"
    }

    /// Escape a value for a Markdown table cell: neutralise pipes and collapse
    /// newlines so a multi-line detail can't break the row.
    private static func md(_ value: String) -> String {
        value
            .replacingOccurrences(of: "|", with: "\\|")
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
    }

    private static let css = """
    :root { --fg:#1b1f24; --muted:#5b6470; --line:#d8dde3; --bg:#fff; --accent:#1f6f8b; }
    * { box-sizing: border-box; }
    body { font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: var(--fg); background: var(--bg); margin: 0; padding: 32px; max-width: 900px; margin-inline: auto; }
    h1 { font-size: 24px; margin: 0 0 4px; }
    h2 { font-size: 19px; margin: 28px 0 10px; border-bottom: 2px solid var(--line); padding-bottom: 4px; }
    h3 { font-size: 16px; margin: 20px 0 8px; color: var(--accent); }
    h4 { font-size: 13px; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: .04em; color: var(--muted); }
    p { margin: 6px 0; }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; background: #f3f5f7; padding: 1px 4px; border-radius: 3px; word-break: break-all; }
    .subtitle { font-size: 18px; color: var(--accent); font-weight: 600; margin-top: 0; }
    .note, .empty { color: var(--muted); font-size: 13px; }
    .empty { font-style: italic; }
    table.meta { border-collapse: collapse; margin: 8px 0; }
    table.meta th { text-align: left; color: var(--muted); font-weight: 600; padding: 3px 16px 3px 0; vertical-align: top; white-space: nowrap; }
    table.meta td { padding: 3px 0; }
    table.data { border-collapse: collapse; width: 100%; margin: 8px 0; font-size: 12.5px; }
    table.data th { text-align: left; background: #f3f5f7; border-bottom: 2px solid var(--line); padding: 5px 8px; }
    table.data td { border-bottom: 1px solid var(--line); padding: 4px 8px; vertical-align: top; word-break: break-word; }
    footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid var(--line); color: var(--muted); font-size: 12px; }
    @page { margin: 18mm; }
    @media print { body { padding: 0; max-width: none; } section.evidence { page-break-inside: avoid; } }
    """
}
