import Foundation

/// Plain-text README written into every export folder. It documents the set's
/// contents and how to turn an HTML report into a PDF - the examiner report
/// ships as print-ready HTML (the examiner controls paper size/margins with
/// their own tool), while the chain-of-custody report is also rendered in-app
/// as a paginated PDF: the formal, file-able custody record. Pure Foundation.
nonisolated enum ExportReadme {
    static let filename = "README.txt"

    /// `filenames` are the artifacts already produced (the README is not in it).
    static func render(inputs: ReportInputs, filenames: [String]) -> String {
        var out = "Strata case export\n"
        out += String(repeating: "=", count: 18) + "\n\n"
        out += "Case:       \(inputs.caseName)\n"
        if !inputs.examiner.isEmpty { out += "Examiner:   \(inputs.examiner)\n" }
        out += "Generated:  \(ReportFormat.display(inputs.generatedAt))\n"
        out += "Endpoints:  \(inputs.hosts.count)\n"
        for host in inputs.hosts {
            out += "  - \(host.displayName) (\(host.kindLabel))\n"
        }
        out += "\nAll timestamps are ISO-8601 / UTC.\n\n"

        out += "Files\n-----\n"
        for name in filenames {
            out += "  \(name)\(describe(name))\n"
        }

        if filenames.contains(where: { $0.hasSuffix("-report.html") || $0.hasSuffix("-chain-of-custody.html") }) {
            out += "\nGenerating a PDF\n----------------\n"
            out += "HTML reports are print-ready. To produce a PDF from one, open it in a\n"
            out += "web browser and choose File > Print > Save as PDF (or Export as PDF).\n"
            if filenames.contains(where: { $0.hasSuffix("-chain-of-custody.pdf") }) {
                out += "The chain-of-custody report is also exported directly as a paginated\n"
                out += "PDF - the formal custody record.\n"
            }
        }

        out += "\nGenerated by Strata.\n"
        return out
    }

    private static func describe(_ name: String) -> String {
        if name.hasSuffix("-report.md")       { return "  — examiner report (Markdown)" }
        if name.hasSuffix("-report.html")     { return "  — examiner report (HTML; print to PDF)" }
        if name.hasSuffix("-timeline.csv")    { return "  — timeline (CSV)" }
        if name.hasSuffix("-timeline.json")   { return "  — timeline (JSON)" }
        if name.hasSuffix("-findings.csv")    { return "  — findings (CSV)" }
        if name.hasSuffix("-findings.json")   { return "  — findings (JSON)" }
        if name.hasSuffix("-iocmatches.csv")  { return "  — IOC matches (CSV)" }
        if name.hasSuffix("-iocmatches.json") { return "  — IOC matches (JSON)" }
        if name.hasSuffix("-chain-of-custody.pdf")  { return "  — chain-of-custody report (PDF; the formal record)" }
        if name.hasSuffix("-chain-of-custody.md")   { return "  — chain-of-custody report (Markdown)" }
        if name.hasSuffix("-chain-of-custody.html") { return "  — chain-of-custody report (HTML; print to PDF)" }
        if name.hasSuffix("-custody.csv")     { return "  — custody log (CSV)" }
        if name.hasSuffix("-custody.json")    { return "  — custody log (JSON)" }
        return ""
    }
}
