import Foundation

/// Plain-text README written into every export folder. It documents the set's
/// contents and how to turn the HTML report into a PDF - Strata deliberately
/// exports a print-ready HTML rather than rendering PDF in-app, so the examiner
/// controls paper size/margins with their own tool and the pipeline stays pure.
/// Pure Foundation.
nonisolated enum ExportReadme {
    static let filename = "README.txt"

    /// `filenames` are the artifacts already produced (the README is not in it).
    static func render(inputs: ReportInputs, filenames: [String]) -> String {
        var out = "Strata case export\n"
        out += String(repeating: "=", count: 18) + "\n\n"
        out += "Case:       \(inputs.caseName)\n"
        if !inputs.examiner.isEmpty { out += "Examiner:   \(inputs.examiner)\n" }
        out += "Generated:  \(ReportFormat.display(inputs.generatedAt))\n"
        out += "Endpoints:  \(inputs.hosts.count)\n"
        for host in inputs.hosts {
            out += "  - \(host.displayName) (\(host.kindLabel))\n"
        }
        out += "\nAll timestamps are ISO-8601 / UTC.\n\n"

        out += "Files\n-----\n"
        for name in filenames {
            out += "  \(name)\(describe(name))\n"
        }

        if filenames.contains(where: { $0.hasSuffix("-report.html") }) {
            out += "\nGenerating a PDF\n----------------\n"
            out += "Strata exports a print-ready HTML report rather than rendering PDF\n"
            out += "itself. To produce a PDF, open the .html report in a web browser and\n"
            out += "choose File > Print > Save as PDF (or Export as PDF). The report\n"
            out += "paginates per host and prints cleanly.\n"
        }

        out += "\nGenerated by Strata.\n"
        return out
    }

    private static func describe(_ name: String) -> String {
        if name.hasSuffix("-report.md")       { return "  — examiner report (Markdown)" }
        if name.hasSuffix("-report.html")     { return "  — examiner report (HTML; print to PDF)" }
        if name.hasSuffix("-timeline.csv")    { return "  — timeline (CSV)" }
        if name.hasSuffix("-timeline.json")   { return "  — timeline (JSON)" }
        if name.hasSuffix("-findings.csv")    { return "  — findings (CSV)" }
        if name.hasSuffix("-findings.json")   { return "  — findings (JSON)" }
        if name.hasSuffix("-iocmatches.csv")  { return "  — IOC matches (CSV)" }
        if name.hasSuffix("-iocmatches.json") { return "  — IOC matches (JSON)" }
        return ""
    }
}
