import Foundation

/// Renders a `ReportModel` as a self-contained HTML document with embedded,
/// print-friendly CSS (`@page` margins + per-host page breaks). It is authored
/// so a later "Export PDF" pass can feed this exact HTML to WebKit's
/// `createPDF` and get a clean paginated document — no separate PDF layout.
///
/// Every interpolated value is HTML-escaped (`escape`); a finding detail or
/// file path containing `<`, `&`, or quotes can never inject markup.
public nonisolated enum HTMLReportRenderer {
    static let iocRowCap = 500

    public static func render(_ model: ReportModel) -> String {
        var out = ""
        out += "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        out += "<meta charset=\"utf-8\">\n"
        out += "<title>Strata Report — \(escape(model.caseName))</title>\n"
        out += "<style>\n\(css)\n</style>\n</head>\n<body>\n"

        out += "<header class=\"case-header\">\n"
        out += "<h1>Strata Examiner Report</h1>\n"
        out += "<p class=\"subtitle\">\(escape(model.caseName))</p>\n"
        out += "<table class=\"meta\">\n"
        out += metaRow("Examiner", model.examiner.isEmpty ? "—" : model.examiner)
        out += metaRow("Case created", ReportFormat.display(model.createdAt))
        out += metaRow("Report generated", ReportFormat.display(model.generatedAt))
        out += metaRow("Hosts", String(model.hostSections.count))
        out += metaRow("Total findings", String(model.totalFindings))
        out += metaRow("Total IOC matches", String(model.totalIOCMatches))
        if let note = model.severityFilterNote {
            out += metaRow("Severity filter", note)
        }
        out += "</table>\n"
        out += "<p class=\"note\">All timestamps are ISO-8601 / UTC."
        if let note = model.severityFilterNote {
            out += " Findings limited to severities: \(escape(note))."
        }
        out += "</p>\n"

        if !model.caseSeverityCounts.isEmpty {
            out += "<h2>Case severity summary</h2>\n<p class=\"badges\">"
            for entry in model.caseSeverityCounts {
                out += severityBadge(entry.severity, suffix: " · \(entry.count)")
            }
            out += "</p>\n"
        }
        out += "</header>\n"

        // Analyst narrative + bookmarked items - the case story as the analyst
        // pinned it, ahead of the per-host detail.
        if !model.narrative.isEmpty {
            out += "<h2>Analyst narrative</h2>\n"
            out += "<p class=\"narrative\">\(escapeMultiline(model.narrative))</p>\n"
        }
        if !model.bookmarks.isEmpty {
            out += "<h2>Bookmarked items</h2>\n"
            out += "<table class=\"data\">\n<thead><tr>"
            out += "<th>Time</th><th>Tag</th><th>Source</th><th>Item</th><th>Note</th>"
            out += "</tr></thead>\n<tbody>\n"
            for bookmark in model.bookmarks {
                out += "<tr>"
                out += "<td>\(escape(ReportFormat.display(bookmark.timestamp)))</td>"
                out += "<td>\(escape(bookmark.tag?.label ?? "—"))</td>"
                out += "<td>\(escape(bookmark.sourceLabel))</td>"
                out += "<td><code>\(escape(bookmark.title))</code></td>"
                out += "<td>\(escapeMultiline(bookmark.note))</td>"
                out += "</tr>\n"
            }
            out += "</tbody>\n</table>\n"
        }

        for host in model.hostSections {
            out += renderHost(host)
        }

        out += "<footer>Generated by Strata.</footer>\n"
        out += "</body>\n</html>\n"
        return out
    }

    private static func renderHost(_ host: ReportModel.HostSection) -> String {
        var out = "<section class=\"host\">\n"
        let title = host.profile.hostname ?? host.displayName
        out += "<h2>Host: \(escape(title))</h2>\n"
        if host.profile.hostname != nil && host.profile.hostname != host.displayName {
            out += "<p class=\"label\">Evidence label: \(escape(host.displayName))</p>\n"
        }
        out += "<p class=\"source\"><strong>Source:</strong> \(escape(host.kindLabel)) — <code>\(escape(host.sourcePath))</code></p>\n"

        // Host profile.
        out += "<h3>Host profile</h3>\n"
        if host.profile.hasAnyData {
            out += "<table class=\"meta\">\n"
            func row(_ label: String, _ value: String?) {
                if let value, !value.isEmpty { out += metaRow(label, value) }
            }
            row("Operating system", host.profile.osSummary)
            row("Domain", host.profile.domain)
            row("Primary user", host.profile.primaryUser)
            row("Time zone", host.profile.timeZone)
            if !host.profile.ipAddresses.isEmpty {
                row("IP addresses", host.profile.ipAddresses.joined(separator: ", "))
            }
            if let install = host.profile.installDate {
                row("Install date", ReportFormat.display(install))
            }
            if let shutdown = host.profile.lastShutdown {
                row("Last shutdown", ReportFormat.display(shutdown))
            }
            out += "</table>\n"
        } else {
            out += "<p class=\"empty\">No host profile derived — registry not parsed for this host.</p>\n"
        }

        // Summary.
        out += "<h3>Summary</h3>\n<ul class=\"summary\">\n"
        out += "<li>Files: \(host.fileCount)</li>\n"
        out += "<li>Event-log records: \(host.eventCount)</li>\n"
        out += "<li>Registry values: \(host.registryValueCount)</li>\n"
        out += "<li>Findings: \(host.findingCount)</li>\n"
        out += "<li>IOC matches: \(host.iocMatchCount)</li>\n"
        out += "</ul>\n"
        if !host.severityCounts.isEmpty {
            out += "<p class=\"badges\">"
            for entry in host.severityCounts {
                out += severityBadge(entry.severity, suffix: " · \(entry.count)")
            }
            out += "</p>\n"
        }

        // Findings by phase.
        out += "<h3>Findings by kill-chain phase</h3>\n"
        if host.phaseGroups.isEmpty {
            out += "<p class=\"empty\">No findings.</p>\n"
        } else {
            for group in host.phaseGroups {
                out += "<h4>\(escape(group.phase.title))</h4>\n"
                for finding in group.findings {
                    out += renderFinding(finding)
                }
            }
        }

        // IOC matches.
        out += "<h3>IOC matches</h3>\n"
        if host.iocMatches.isEmpty {
            out += "<p class=\"empty\">No IOC matches.</p>\n"
        } else {
            out += "<table class=\"data\">\n<thead><tr>"
            out += "<th>Timestamp</th><th>Kind</th><th>Value</th><th>Location</th><th>Context</th>"
            out += "</tr></thead>\n<tbody>\n"
            for match in host.iocMatches.prefix(iocRowCap) {
                let loc = ExportRowBuilder.locationParts(match.location)
                out += "<tr>"
                out += cell(ReportFormat.display(match.timestamp))
                out += cell(match.iocKind.label)
                out += cell(match.iocValue)
                out += cell(loc.detail)
                out += cell(match.context)
                out += "</tr>\n"
            }
            out += "</tbody>\n</table>\n"
            if host.iocMatches.count > iocRowCap {
                out += "<p class=\"note\">… and \(host.iocMatches.count - iocRowCap) more (see the IOC-match CSV/JSON export).</p>\n"
            }
        }

        // Timeline excerpt.
        out += "<h3>Timeline excerpt (findings, chronological)</h3>\n"
        if host.timelineExcerpt.isEmpty {
            out += "<p class=\"empty\">No timestamped findings.</p>\n"
        } else {
            out += "<table class=\"data\">\n<thead><tr>"
            out += "<th>Timestamp</th><th>Severity</th><th>Phase</th><th>Finding</th>"
            out += "</tr></thead>\n<tbody>\n"
            for finding in host.timelineExcerpt {
                out += "<tr>"
                out += cell(ReportFormat.display(finding.timestamp))
                out += cell(finding.severity.label)
                out += cell(finding.phase.title)
                out += cell(finding.title)
                out += "</tr>\n"
            }
            out += "</tbody>\n</table>\n"
        }

        out += "</section>\n"
        return out
    }

    private static func renderFinding(_ finding: Finding) -> String {
        var out = "<div class=\"finding sev-\(finding.severity.rawValue)\">\n"
        out += "<p class=\"finding-title\">"
        out += severityBadge(finding.severity, suffix: "")
        out += " <span class=\"title\">\(escape(finding.title))</span>"
        if let technique = finding.technique {
            out += " <span class=\"attack\">\(escape(technique.attackID)) \(escape(technique.name))</span>"
        }
        if finding.timestamp != nil {
            out += " <span class=\"ts\">\(escape(ReportFormat.display(finding.timestamp)))</span>"
        }
        out += "</p>\n"
        let detail = finding.detail.trimmingCharacters(in: .whitespacesAndNewlines)
        if !detail.isEmpty {
            out += "<p class=\"finding-detail\">\(escapeMultiline(detail))</p>\n"
        }
        if !finding.evidencePaths.isEmpty {
            let paths = finding.evidencePaths.map { "<code>\(escape($0))</code>" }.joined(separator: ", ")
            out += "<p class=\"evidence\"><em>Evidence:</em> \(paths)</p>\n"
        }
        out += "</div>\n"
        return out
    }

    // MARK: - Small helpers

    private static func metaRow(_ label: String, _ value: String) -> String {
        "<tr><th>\(escape(label))</th><td>\(escape(value))</td></tr>\n"
    }

    private static func cell(_ value: String) -> String {
        "<td>\(escape(value))</td>"
    }

    private static func severityBadge(_ severity: Severity, suffix: String) -> String {
        "<span class=\"sev-badge sev-\(severity.rawValue)\">\(escape(severity.label))\(escape(suffix))</span>"
    }

    /// HTML-escape, but preserve line breaks as `<br>` for multi-line detail.
    private static func escapeMultiline(_ value: String) -> String {
        escape(value).replacingOccurrences(of: "\n", with: "<br>\n")
    }

    /// Escape the five HTML-significant characters. `&` first so we don't
    /// double-escape the entities we introduce.
    static func escape(_ value: String) -> String {
        var result = value
        result = result.replacingOccurrences(of: "&", with: "&amp;")
        result = result.replacingOccurrences(of: "<", with: "&lt;")
        result = result.replacingOccurrences(of: ">", with: "&gt;")
        result = result.replacingOccurrences(of: "\"", with: "&quot;")
        result = result.replacingOccurrences(of: "'", with: "&#39;")
        return result
    }

    // MARK: - Stylesheet

    private static let css = """
    :root {
      --fg: #1b1f24; --muted: #5b6470; --line: #d8dde3; --bg: #ffffff;
      --accent: #1f6f8b;
      --info: #6b7280; --low: #2f855a; --medium: #b7791f;
      --high: #c05621; --critical: #c53030;
    }
    * { box-sizing: border-box; }
    body {
      font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: var(--fg); background: var(--bg); margin: 0; padding: 32px;
      max-width: 900px; margin-inline: auto;
    }
    h1 { font-size: 24px; margin: 0 0 4px; }
    h2 { font-size: 19px; margin: 28px 0 10px; border-bottom: 2px solid var(--line); padding-bottom: 4px; }
    h3 { font-size: 16px; margin: 20px 0 8px; color: var(--accent); }
    h4 { font-size: 14px; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: .04em; color: var(--muted); }
    p { margin: 6px 0; }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; background: #f3f5f7; padding: 1px 4px; border-radius: 3px; word-break: break-all; }
    .subtitle { font-size: 18px; color: var(--accent); font-weight: 600; margin-top: 0; }
    .note, .label, .empty { color: var(--muted); font-size: 13px; }
    .empty { font-style: italic; }
    table.meta { border-collapse: collapse; margin: 8px 0; }
    table.meta th { text-align: left; color: var(--muted); font-weight: 600; padding: 3px 16px 3px 0; vertical-align: top; white-space: nowrap; }
    table.meta td { padding: 3px 0; }
    table.data { border-collapse: collapse; width: 100%; margin: 8px 0; font-size: 12.5px; }
    table.data th { text-align: left; background: #f3f5f7; border-bottom: 2px solid var(--line); padding: 5px 8px; }
    table.data td { border-bottom: 1px solid var(--line); padding: 4px 8px; vertical-align: top; word-break: break-word; }
    ul.summary { margin: 6px 0; padding-left: 20px; }
    .finding { border-left: 3px solid var(--line); padding: 6px 0 6px 12px; margin: 8px 0; }
    .finding .title { font-weight: 600; }
    .finding-detail { color: #333; }
    .finding .attack { font-family: ui-monospace, monospace; font-size: 11.5px; color: var(--muted); }
    .finding .ts { font-size: 11.5px; color: var(--muted); }
    .evidence { font-size: 12px; color: var(--muted); }
    .evidence code { background: #f3f5f7; }
    .badges { margin: 6px 0; }
    .sev-badge { display: inline-block; font-size: 11px; font-weight: 700; color: #fff; padding: 1px 7px; border-radius: 9px; margin-right: 6px; }
    .sev-0 { background: var(--info); } .finding.sev-0 { border-left-color: var(--info); }
    .sev-1 { background: var(--low); } .finding.sev-1 { border-left-color: var(--low); }
    .sev-2 { background: var(--medium); } .finding.sev-2 { border-left-color: var(--medium); }
    .sev-3 { background: var(--high); } .finding.sev-3 { border-left-color: var(--high); }
    .sev-4 { background: var(--critical); } .finding.sev-4 { border-left-color: var(--critical); }
    footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid var(--line); color: var(--muted); font-size: 12px; }
    @page { margin: 18mm; }
    @media print {
      body { padding: 0; max-width: none; }
      section.host { page-break-before: always; }
      table.data { font-size: 10.5px; }
      a, code { word-break: break-all; }
    }
    """
}
