import Foundation

/// Renders a `ReportModel` as GitHub-flavored Markdown. The narrative report is
/// a summary - bulk rows (the full timeline, every IOC match) belong in the
/// CSV/JSON exports, so IOC tables here are capped with a "see export" note.
public nonisolated enum MarkdownReportRenderer {
    /// Maximum IOC-match rows shown in the narrative before truncating.
    static let iocRowCap = 200

    public static func render(_ model: ReportModel) -> String {
        var out = ""

        out += "# Strata Examiner Report — \(model.caseName)\n\n"
        out += "| | |\n|---|---|\n"
        out += "| Case | \(model.caseName) |\n"
        out += "| Examiner | \(model.examiner.isEmpty ? "—" : model.examiner) |\n"
        out += "| Case created | \(ReportFormat.display(model.createdAt)) |\n"
        out += "| Report generated | \(ReportFormat.display(model.generatedAt)) |\n"
        out += "| Hosts | \(model.hostSections.count) |\n"
        out += "| Total findings | \(model.totalFindings) |\n"
        out += "| Total IOC matches | \(model.totalIOCMatches) |\n"
        if let note = model.severityFilterNote {
            out += "| Severity filter | \(note) |\n"
        }
        out += "\n_All timestamps are ISO-8601 / UTC._\n"
        if let note = model.severityFilterNote {
            out += "_Findings limited to severities: \(note)._\n"
        }
        out += "\n"

        if !model.caseSeverityCounts.isEmpty {
            out += "## Case severity summary\n\n"
            for entry in model.caseSeverityCounts {
                out += "- **\(entry.severity.label):** \(entry.count)\n"
            }
            out += "\n"
        }

        for host in model.hostSections {
            out += renderHost(host)
        }

        out += "---\n\n_Generated by Strata._\n"
        return out
    }

    private static func renderHost(_ host: ReportModel.HostSection) -> String {
        var out = ""
        let title = host.profile.hostname ?? host.displayName
        out += "## Host: \(title)\n\n"
        if host.profile.hostname != nil && host.profile.hostname != host.displayName {
            out += "_Evidence label: \(host.displayName)_\n\n"
        }
        out += "**Source:** \(host.kindLabel) — `\(host.sourcePath)`\n\n"

        // Host profile (only populated fields).
        out += "### Host profile\n\n"
        if host.profile.hasAnyData {
            out += "| Field | Value |\n|---|---|\n"
            func row(_ label: String, _ value: String?) {
                if let value, !value.isEmpty { out += "| \(label) | \(value) |\n" }
            }
            row("Operating system", host.profile.osSummary)
            row("Domain", host.profile.domain)
            row("Primary user", host.profile.primaryUser)
            row("Time zone", host.profile.timeZone)
            if !host.profile.ipAddresses.isEmpty {
                row("IP addresses", host.profile.ipAddresses.joined(separator: ", "))
            }
            if let install = host.profile.installDate {
                row("Install date", ReportFormat.display(install))
            }
            if let shutdown = host.profile.lastShutdown {
                row("Last shutdown", ReportFormat.display(shutdown))
            }
            out += "\n"
        } else {
            out += "_No host profile derived — registry not parsed for this host._\n\n"
        }

        // Summary counts.
        out += "### Summary\n\n"
        out += "- Files: \(host.fileCount)\n"
        out += "- Event-log records: \(host.eventCount)\n"
        out += "- Registry values: \(host.registryValueCount)\n"
        out += "- Findings: \(host.findingCount)\n"
        out += "- IOC matches: \(host.iocMatchCount)\n"
        if !host.severityCounts.isEmpty {
            let parts = host.severityCounts.map { "\($0.severity.label) \($0.count)" }
            out += "- Severity: \(parts.joined(separator: ", "))\n"
        }
        out += "\n"

        // Findings grouped by kill-chain phase.
        out += "### Findings by kill-chain phase\n\n"
        if host.phaseGroups.isEmpty {
            out += "_No findings._\n\n"
        } else {
            for group in host.phaseGroups {
                out += "#### \(group.phase.title)\n\n"
                for finding in group.findings {
                    out += renderFinding(finding)
                }
            }
        }

        // IOC matches.
        out += "### IOC matches\n\n"
        if host.iocMatches.isEmpty {
            out += "_No IOC matches._\n\n"
        } else {
            out += "| Timestamp | Kind | Value | Location | Context |\n|---|---|---|---|---|\n"
            for match in host.iocMatches.prefix(iocRowCap) {
                let loc = ExportRowBuilder.locationParts(match.location)
                out += "| \(ReportFormat.display(match.timestamp)) "
                out += "| \(match.iocKind.label) | \(escapeCell(match.iocValue)) "
                out += "| \(escapeCell(loc.detail)) | \(escapeCell(match.context)) |\n"
            }
            if host.iocMatches.count > iocRowCap {
                out += "\n_… and \(host.iocMatches.count - iocRowCap) more (see the IOC-match CSV/JSON export)._\n"
            }
            out += "\n"
        }

        // Timeline excerpt = findings carrying a timestamp, chronological.
        out += "### Timeline excerpt (findings, chronological)\n\n"
        if host.timelineExcerpt.isEmpty {
            out += "_No timestamped findings._\n\n"
        } else {
            out += "| Timestamp | Severity | Phase | Finding |\n|---|---|---|---|\n"
            for finding in host.timelineExcerpt {
                out += "| \(ReportFormat.display(finding.timestamp)) "
                out += "| \(finding.severity.label) | \(finding.phase.title) "
                out += "| \(escapeCell(finding.title)) |\n"
            }
            out += "\n"
        }

        return out
    }

    private static func renderFinding(_ finding: Finding) -> String {
        var out = "- **[\(finding.severity.label)]** \(finding.title)"
        if let technique = finding.technique {
            out += " — `\(technique.attackID)` \(technique.name)"
        }
        if finding.timestamp != nil {
            out += " — \(ReportFormat.display(finding.timestamp))"
        }
        out += "\n"
        let detail = finding.detail.trimmingCharacters(in: .whitespacesAndNewlines)
        if !detail.isEmpty {
            // Indent each line so multi-line details stay under the bullet.
            for line in detail.split(separator: "\n", omittingEmptySubsequences: false) {
                out += "  \(line)\n"
            }
        }
        if !finding.evidencePaths.isEmpty {
            out += "  _Evidence:_ \(finding.evidencePaths.joined(separator: "; "))\n"
        }
        out += "\n"
        return out
    }

    /// Neutralise pipes and newlines so a value can't break a Markdown table row.
    private static func escapeCell(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
            .replacingOccurrences(of: "|", with: "\\|")
    }
}
