import Foundation

/// Render-ready representation of an examiner report. `ReportModelBuilder`
/// produces it once; the Markdown and HTML renderers format it without
/// repeating any content-selection logic, so the two formats stay in lockstep.
public nonisolated struct ReportModel: Sendable {
    /// A severity with its count, used for the summary rollups.
    public struct SeverityCount: Sendable {
        public let severity: Severity
        public let count: Int
    }

    /// Findings sharing one kill-chain phase, severity-sorted (high → low).
    public struct PhaseGroup: Sendable {
        public let phase: KillChainPhase
        public let findings: [Finding]
    }

    public struct HostSection: Sendable {
        public let displayName: String
        public let kindLabel: String
        public let sourcePath: String
        public let profile: HostProfile
        public let fileCount: Int
        public let eventCount: Int
        public let registryValueCount: Int
        public let findingCount: Int
        public let iocMatchCount: Int
        /// Non-zero severities only, high → low.
        public let severityCounts: [SeverityCount]
        /// Non-empty phases only, in kill-chain order.
        public let phaseGroups: [PhaseGroup]
        public let iocMatches: [IOCMatch]
        /// Findings carrying a timestamp, chronological - the "timeline excerpt"
        /// of the narrative (the full timeline lives in the CSV/JSON export).
        public let timelineExcerpt: [Finding]
    }

    public let caseName: String
    public let examiner: String
    public let createdAt: Date
    public let generatedAt: Date
    /// On-device AI-generated executive summary of the findings; empty when
    /// none was generated. Rendered above the analyst narrative.
    public let executiveSummary: String
    /// Validated, evidence-anchored claims listed under the executive summary;
    /// empty for legacy / prose-path summaries.
    public let summaryClaims: [SummaryClaim]
    /// The evidence-reference validation report, surfaced as a caveat; `nil`
    /// when the summary was not produced by the validated structured path.
    public let summaryValidation: SummaryValidationReport?
    /// Tier-accurate "how this summary was generated" line for the report — the
    /// legal-weight record must state whether inference ran on-device or left the
    /// host (Apple Private Cloud Compute / third-party cloud), never assume
    /// sovereign. Derived in the builder from the recorded model label.
    public let summaryProvenanceNote: String
    /// The analyst's free-form case narrative; empty when none was written.
    public let narrative: String
    /// Analyst bookmarks, chronological by the target's own timestamp
    /// (undated last) - the pinned "story" items.
    public let bookmarks: [Annotation]
    public let hostSections: [HostSection]
    public let totalFindings: Int
    public let totalIOCMatches: Int
    /// Case-wide severity rollup, high → low, non-zero only.
    public let caseSeverityCounts: [SeverityCount]
    /// Set when the report was filtered to a subset of severities, e.g.
    /// "High, Critical". `nil` when every severity is included - the renderers
    /// surface it so the reader knows the findings are a filtered view.
    public let severityFilterNote: String?

    /// Tier-accurate provenance line for an AI summary. The examiner report must
    /// say HOW the summary was produced, so an off-device (Apple Private Cloud
    /// Compute or third-party) summary is never misreported as on-device. Keys
    /// off the recorded `SovereigntyTier` (the persisted source of truth); the
    /// label supplies the third-party model's name for display.
    public static func summaryProvenanceNote(tier: SovereigntyTier, modelLabel: String) -> String {
        let how: String
        switch tier {
        case .applePrivateCloud:
            how = "Generated via Apple Private Cloud Compute (off-device; only finding summaries — titles, details, paths — left this host, never raw evidence)"
        case .thirdPartyCloud:
            how = "Generated by \(modelLabel) — a third-party cloud model (finding summaries left this host; raw evidence did not)"
        case .onDevice:
            how = "Generated on-device by Apple Intelligence"
        }
        return "\(how). Examiner review recommended."
    }
}
